// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2f26a279-21f4-4ba9-a1e7-323aa83920e7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLukasAccessChange();
void onMatthiasAccessChange();

String homeStatusMsg;
float temperatureSensor;
bool lukasAccess;
bool matthiasAccess;
bool switchLED;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(homeStatusMsg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatureSensor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lukasAccess, READWRITE, ON_CHANGE, onLukasAccessChange);
  ArduinoCloud.addProperty(matthiasAccess, READWRITE, ON_CHANGE, onMatthiasAccessChange);
  ArduinoCloud.addProperty(switchLED, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
